In [3]:
pip install torch


[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: /opt/homebrew/opt/python@3.11/bin/python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [4]:
import torch 

In [12]:
#Step 1: Forward pass
N = 10 #number of elemnts per batch 
D_in = 1 #input dimension
D_out = 1 #output dimension

X = torch.randn(N, D_in)
# print(X)

true_W = torch.tensor([[2.0]])
true_B = torch.tensor(1.0)
y_true = X @ true_W + true_B + torch.randn(N, D_out) * 0.1
# print(y_true)

In [13]:
W = torch.randn(D_in, D_out, requires_grad=True)
B = torch.randn(1, requires_grad=True)

In [14]:
#forward pass
y_hat = X @ W + B

In [ ]:
print(y_hat)
print(y_true)

tensor([[-0.2624],
        [-0.2944],
        [-0.1435],
        [-0.5707],
        [-0.3596],
        [-0.1235],
        [-0.0055],
        [-0.1366],
        [-0.2511],
        [-0.5237]], grad_fn=<AddBackward0>)
tensor([[ 0.0966],
        [ 0.2897],
        [-0.6713],
        [ 2.5860],
        [ 0.9717],
        [-0.9778],
        [-1.9511],
        [-0.8893],
        [ 0.1880],
        [ 2.2899]])


In [ ]:
#Loss Calculation 
squared_error = (y_hat - y_true) ** 2 
loss = squared_error.mean()

#Gradient calculation
loss.backward() #This function populates the .gradient parameter for all of our tensors with requires_grad = True

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [19]:
print(W.grad)
print(B.grad)

tensor([[-1.7997]])
tensor([-1.8414])


In [ ]:
#One step of gradient descent: 
W_new = W - learning_rate * W.grad
B_new = B - learning_rate * B.grad

In [21]:
#Entire training Loop:

#Hyperparameters
epochs, lr = 100, 0.01
#Initialization of parameters 
W = torch.randn(D_in, D_out, requires_grad=True)
b = torch.randn(1, requires_grad=True)

for epoch in range(epochs): 
    if epoch % 10 == 0: 
        print(f"Epoch number: {epoch}, loss: {loss.item()}")
    y_hat = X @ W + b 
    loss = torch.mean(((y_true - y_hat) ** 2))

    loss.backward() 
    with torch.no_grad(): 
        W -= lr * W.grad
        b -= lr * b.grad

    W.grad.zero_()
    b.grad.zero_() 


Epoch number: 0, loss: 2.5676589012145996
Epoch number: 10, loss: 4.628843307495117
Epoch number: 20, loss: 3.707353115081787
Epoch number: 30, loss: 3.0160274505615234
Epoch number: 40, loss: 2.483874797821045
Epoch number: 50, loss: 2.064929723739624
Epoch number: 60, loss: 1.728843331336975
Epoch number: 70, loss: 1.4551080465316772
Epoch number: 80, loss: 1.2294971942901611
Epoch number: 90, loss: 1.0418609380722046


In [22]:
# nn.Linear module 
D_in, D_out = 1, 1
# Creating a linear layer 
linear_layer = torch.nn.Linear(in_features=D_in, out_features=D_out)

print(f"Layer's Weight: {linear_layer.weight}")
print(f"Layer's Bias: {linear_layer.bias}")

# Can use the linear layer as a function
y_hat_nn = linear_layer(X)
print(f"Linear Layer Output: {y_hat_nn}")

Layer's Weight: Parameter containing:
tensor([[-0.7677]], requires_grad=True)
Layer's Bias: Parameter containing:
tensor([-0.7503], requires_grad=True)
Linear Layer Output: tensor([[-0.4483],
        [-0.5493],
        [-0.0728],
        [-1.4220],
        [-0.7553],
        [-0.0096],
        [ 0.3632],
        [-0.0509],
        [-0.4126],
        [-1.2737]], grad_fn=<AddmmBackward0>)


In [24]:
## nn.RELU activation function
relu = torch.nn.ReLU()
test = torch.randn(5, 1) 
activated_test = relu(test)
print(f"test: {test}")
print(f"activated_test: {activated_test}")

test: tensor([[-0.3788],
        [-1.6089],
        [-0.4575],
        [-0.4349],
        [ 0.6318]])
activated_test: tensor([[0.0000],
        [0.0000],
        [0.0000],
        [0.0000],
        [0.6318]])
