In [1]:
import torch 
import numpy as np

In [2]:
# Creating tensor for input data 
sample_data = [[1,2,3], [4,5,6]]
x_data = torch.tensor(sample_data)
print(x_data)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [3]:
# Creating tensor from numpy array 
numpy_arr = np.array(sample_data)
tensor_numpy_arr = torch.from_numpy(numpy_arr)
print(tensor_numpy_arr)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [7]:
# Creating tensor from another tensor 
tensor_ones = torch.ones_like(tensor_numpy_arr)
tensor_rand = torch.randn_like(tensor_numpy_arr, dtype=torch.float)
print(tensor_ones)
tensor_rand

tensor([[1, 1, 1],
        [1, 1, 1]])


tensor([[-1.2609, -0.0547, -0.1530],
        [ 1.3181,  1.1002,  1.1226]])

In [11]:
# Random Tensor Initialization 
shape = (2,3)
ones = torch.ones(shape)
print(ones)
zeroes = torch.zeros(shape)
print(zeroes)
random = torch.rand(shape)
print(random)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.0945, 0.8907, 0.8646],
        [0.8607, 0.7189, 0.2073]])


In [12]:
#Tensor Attributes 
print(tensor_numpy_arr.dtype)
print(tensor_numpy_arr.shape)
print(tensor_numpy_arr.device)

torch.int64
torch.Size([2, 3])
cpu
